Partial implementation of user registration plus email, images and user repositories
kokoaespol/ChocoAPI pull request #23
Opened 2022-07-28 22:36 UTC by aloussase

2022-07-28 23:36 UTC, adriandelgado requested changes

2022-07-28 23:36 UTC, adriandelgado commented on src/erro.rs
> +            AppError::UnprocessableEntity => (),
I think the response should indicate which field is erroneous.

2022-07-28 23:36 UTC, adriandelgado commented on src/models/users.rs
> +impl IntoResponse for User {
Instead of implementing `IntoResponse`, I think we should use [`Json<User>`](https://docs.rs/axum/latest/axum/struct.Json.html).
Using `Json<User>` as the return value is more explicit. `IntoResponse` is better suited for more complex cases.

2022-07-28 23:36 UTC, adriandelgado commented on src/models/users.rs
> +// Clippy me obligó a hacer esto
English please xD

2022-07-28 23:36 UTC, adriandelgado commented on src/erro.rs
> +    UnprocessableEntity,
This error variant should hold a `HashMap` (field, errors).

2022-07-28 23:36 UTC, adriandelgado commented on src/repositories/image_repository.rs
> +        let file_path = Path::new("image_uuid").join(format!("image_file_{image_id}"));
You can construct a `PathBuf` from an `Iterator`.
https://doc.rust-lang.org/stable/std/path/struct.PathBuf.html#examples

2022-07-28 23:49 UTC, adriandelgado commented on Cargo.toml
> +axum = { version = "0.5.14", features = ["headers", "multipart"] }
Please downgrade to 0.5.13. See https://github.com/tokio-rs/axum/issues/1202

2022-07-29 16:32 UTC, Neoterux commented
Please, make the changes described [here](https://github.com/kokoaespol/ChocoAPI/pull/23#discussion_r932760014)

2022-07-29 17:01 UTC, Neoterux approved these changes
Approved

2022-07-29 17:03 UTC, merged